### ISSUE TITLE
IndexError:

### ISSUE THREAD

**Issue by grvhi** [lektor/lektor-markdown-header-anchors#2]
After installing this plugin, I get the following error/traceback on building my project:

```
Traceback (most recent call last):
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 702, in update
    yield ctx
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 924, in build_artifact
    build_func(artifact)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/build_programs.py", line 169, in build_artifact
    self.source['_template'], this=self.source)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 592, in render_template_into
    this=this, **extra)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/environment.py", line 466, in render_template
    return self.jinja_env.get_or_select_template(name).render(ctx)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/george/sites/lektor-test/templates/docs-layout.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/george/sites/lektor-test/templates/base.html", line 73, in top-level template code
    {% block container %}{% endblock %}
  File "/Users/george/sites/lektor-test/templates/docs-layout.html", line 158, in block "container"
    {{ this.body }}
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/types/formats.py", line 83, in __html__
    self.__render()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/types/formats.py", line 63, in __render
    self.__html, self.__meta = markdown_to_html(self.source)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/types/formats.py", line 50, in markdown_to_html
    ctx.env.plugin_controller.emit('markdown-meta-postprocess', meta=meta)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/pluginsystem.py", line 160, in emit
    rv[plugin.id] = handler(**kwargs)
  File "/Users/george/Library/Caches/Lektor/packages/90a686673295c43fdbd9176a65a6a19d/lektor_markdown_header_anchors.py", line 40, in on_markdown_meta_postprocess
    stack[-1].append(TocEntry(anchor, title, []))
IndexError: list index out of range
```

Everything works exactly as expected without the plugin installed.

**Comment by mitsuhiko** [comment]
This is caused by a page like this:

```
### headline high level
a

## headline lower level
b
```

0.2 changes it so that it no longer errors but the TOC will still be weird.
